import Foundation

/// The four locations supported by the low-barrier exercise catalog.
enum ExerciseScene: String, CaseIterable, Codable, Sendable {
    case privateIndoor = "私人室内"
    case publicIndoor = "公共室内"
    case publicOutdoor = "公共室外"
    case privateOrOpenOutdoor = "私人/开放室外"

    init?(title: String) {
        let normalized = title
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .replacingOccurrences(of: "／", with: "/")
        self.init(rawValue: normalized)
    }

    /// Preserves the wording used by the source workbook when an audit label is needed.
    var sourceTitle: String {
        switch self {
        case .privateOrOpenOutdoor:
            return "私人／开放室外"
        default:
            return rawValue
        }
    }
}

enum ExerciseType: String, Codable, Sendable {
    case aerobic = "有氧运动"
    case dynamicResistance = "动态抗阻运动"
    case isometric = "等长运动"

    var isAerobic: Bool { self == .aerobic }
}

enum ExerciseEnergyTier: Int, CaseIterable, Codable, Sendable {
    case low = 1
    case medium = 2
    case high = 3

    init?(title: String) {
        switch title.trimmingCharacters(in: .whitespacesAndNewlines) {
        case "精力低": self = .low
        case "精力一般": self = .medium
        case "精力较好": self = .high
        default: return nil
        }
    }

    var title: String {
        switch self {
        case .low: return "精力低"
        case .medium: return "精力一般"
        case .high: return "精力较好"
        }
    }
}

enum ExerciseContext: String, CaseIterable, Codable, Hashable, Sendable {
    case afterMeal = "饭后"
    case afterSitting = "久坐后"
    case afterStress = "压力后"
    case sleepDeprived = "睡眠不足"
    case afterActivity = "刚活动后"
    case noSpecialCondition = "无特殊情况"
}

/// Every catalog item explicitly declares its score for each selectable context.
/// Valid scored values are +3, +1, -1 and -3. "无特殊情况" always contributes 0.
struct ExerciseContextScores: Equatable, Sendable {
    let afterMeal: Int
    let afterSitting: Int
    let afterStress: Int
    let sleepDeprived: Int
    let afterActivity: Int

    subscript(context: ExerciseContext) -> Int {
        switch context {
        case .afterMeal: return afterMeal
        case .afterSitting: return afterSitting
        case .afterStress: return afterStress
        case .sleepDeprived: return sleepDeprived
        case .afterActivity: return afterActivity
        case .noSpecialCondition: return 0
        }
    }
}

struct LowBarrierExercise: Identifiable, Equatable, Sendable {
    let id: String
    let scene: ExerciseScene
    let name: String
    let type: ExerciseType
    /// Fixed, reviewed copy from the source workbook. It is not generated by GPT.
    let movementAdvice: String
    /// Fixed, reviewed copy from the source workbook. It is not generated by GPT.
    let intensityAdvice: String
    let systemImageName: String
    let assetImageName: String?
    let energyTier: ExerciseEnergyTier
    let contextScores: ExerciseContextScores
    let catalogOrder: Int

    var movementAdviceSteps: [String] {
        adviceLines(from: movementAdvice)
    }

    var intensityAdviceSteps: [String] {
        adviceLines(from: intensityAdvice)
    }

    func assetImageName(for presentationSex: ExercisePresentationSex) -> String? {
        guard let assetImageName else { return nil }
        return presentationSex == .male ? "\(assetImageName)Male" : assetImageName
    }

    private func adviceLines(from advice: String) -> [String] {
        advice
            .split(whereSeparator: \.isNewline)
            .map(String.init)
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
    }
}

struct ExerciseRecommendation: Identifiable, Equatable, Sendable {
    var id: String { exercise.id }
    let exercise: LowBarrierExercise
    let score: Int
    let energyScore: Int
    let contextScore: Int
}

enum LowBarrierExerciseCatalog {
    static let all: [LowBarrierExercise] = [
        make(
            id: "private-indoor-march-in-place",
            scene: .privateIndoor,
            name: "原地踏步",
            type: .aerobic,
            movementAdvice: """
            ① 身体站直，双脚交替抬起；
            ② 手臂自然前后摆动；
            ③ 脚步轻稳，不需要把膝盖抬得很高。
            """,
            intensityAdvice: "呼吸稍快，但仍能完整说话，不能轻松唱歌。如果只能说几个词，请放慢踏步速度。",
            systemImageName: "figure.highintensity.intervaltraining",
            assetImageName: "ExerciseMarchInPlace",
            energyTier: .medium,
            scores: scores(1, 3, 3, -1, -1),
            order: 0
        ),
        make(
            id: "private-indoor-sit-to-stand",
            scene: .privateIndoor,
            name: "坐站练习",
            type: .dynamicResistance,
            movementAdvice: """
            ① 双脚踩稳，坐在稳定座椅上；
            ② 身体稍向前倾，缓慢站起；
            ③ 再慢慢坐下，不要突然落座。
            """,
            intensityAdvice: "动作时保持呼吸，并能说出简短句子。如果需要憋气、动作变形或无法平稳说话，请减少次数或降低速度。",
            systemImageName: "figure.stand",
            assetImageName: "ExerciseSitToStand",
            energyTier: .medium,
            scores: scores(-1, 3, -1, -1, -1),
            order: 1
        ),
        make(
            id: "private-indoor-wall-push-up",
            scene: .privateIndoor,
            name: "靠墙俯卧撑",
            type: .dynamicResistance,
            movementAdvice: """
            ① 双手撑墙，与肩膀大致同高；
            ② 身体保持直线，缓慢靠近墙面；
            ③ 推回时呼气，不要塌腰或耸肩。
            """,
            intensityAdvice: "动作过程中应能正常呼吸并说出简短句子。如果必须憋气才能推回，请更靠近墙面站立或减少次数。",
            systemImageName: "figure.strengthtraining.traditional",
            assetImageName: "ExerciseWallPushUp",
            energyTier: .medium,
            scores: scores(-1, 1, -1, -1, -1),
            order: 2
        ),
        make(
            id: "private-indoor-wall-sit",
            scene: .privateIndoor,
            name: "靠墙静蹲",
            type: .isometric,
            movementAdvice: """
            ① 背部贴墙，双脚向前迈半步；
            ② 缓慢下滑至舒适的浅蹲位置；
            ③ 膝盖朝向脚尖，保持身体稳定。
            """,
            intensityAdvice: "采用浅角度、短时间保持，并在每次保持后充分休息；全程正常呼吸。如果出现憋气、明显发抖、头晕或无法说出短句，请立即站起休息。不要把它设计成连续 10–20 分钟的保持动作。",
            systemImageName: "figure.strengthtraining.functional",
            assetImageName: "ExerciseWallSit",
            energyTier: .high,
            scores: scores(-3, -1, -3, -3, -3),
            order: 3
        ),
        make(
            id: "private-indoor-seated-alternating-knee-lift",
            scene: .privateIndoor,
            name: "坐姿交替抬膝",
            type: .aerobic,
            movementAdvice: """
            ① 坐在稳定座椅前半部，双脚踩地；
            ② 左右交替抬膝，抬到舒适高度；
            ③ 上身保持直立，手臂可轻轻摆动。
            """,
            intensityAdvice: "呼吸稍快，但仍能完整说话，不能轻松唱歌。如果腰背紧张、身体明显后仰或只能说几个词，请降低抬膝高度并放慢节奏。",
            systemImageName: "figure.cooldown",
            assetImageName: "ExerciseSeatedAlternatingKneeLift",
            energyTier: .low,
            scores: scores(1, 3, 1, 3, 1),
            order: 4
        ),
        make(
            id: "private-indoor-seated-knee-extension",
            scene: .privateIndoor,
            name: "坐姿伸膝",
            type: .dynamicResistance,
            movementAdvice: """
            ① 坐稳，双脚先踩在地面；
            ② 单侧小腿缓慢向前伸直；
            ③ 短暂停顿后缓慢放下，左右交替。
            """,
            intensityAdvice: "动作时保持自然呼吸，并能说出简短句子。如果需要后仰借力、膝部疼痛或无法控制小腿缓慢落下，请减小伸直幅度或减少次数。",
            systemImageName: "figure.flexibility",
            assetImageName: "ExerciseSeatedKneeExtension",
            energyTier: .low,
            scores: scores(-1, 3, 1, 3, 1),
            order: 5
        ),

        make(
            id: "public-indoor-slow-walk",
            scene: .publicIndoor,
            name: "慢走",
            type: .aerobic,
            movementAdvice: """
            ① 保持自然步幅，不刻意迈大步；
            ② 肩膀放松，手臂自然摆动；
            ③ 目视前方，保持稳定节奏。
            """,
            intensityAdvice: "呼吸稍快，但仍能完整说话，不能轻松唱歌。如果无法连续说完一句话，请主动放慢。",
            systemImageName: "figure.walk",
            assetImageName: "ExerciseSlowWalk",
            energyTier: .low,
            scores: scores(3, 3, 3, 3, 3),
            order: 6
        ),
        make(
            id: "public-indoor-march-in-place",
            scene: .publicIndoor,
            name: "原地踏步",
            type: .aerobic,
            movementAdvice: """
            ① 双脚交替抬起，脚步轻轻落地；
            ② 身体保持直立，不左右摇晃；
            ③ 从较慢节奏开始，再逐渐加快。
            """,
            intensityAdvice: "呼吸稍快，但仍能完整说话，不能轻松唱歌。如果只能说几个词，请减慢节奏或暂停。",
            systemImageName: "figure.highintensity.intervaltraining",
            assetImageName: "ExerciseMarchInPlace",
            energyTier: .medium,
            scores: scores(1, 3, 3, -1, -1),
            order: 7
        ),
        make(
            id: "public-indoor-side-step",
            scene: .publicIndoor,
            name: "侧向踏步",
            type: .aerobic,
            movementAdvice: """
            ① 向左迈一步，再把右脚并拢；
            ② 向右重复，左右交替；
            ③ 膝盖微屈，全程不跳跃。
            """,
            intensityAdvice: "呼吸稍快，但仍能完整说话，不能轻松唱歌。如果说话开始断断续续，请减小步幅或放慢速度。",
            systemImageName: "figure.cross.training",
            assetImageName: "ExerciseSideStep",
            energyTier: .medium,
            scores: scores(1, 3, 3, -1, -1),
            order: 8
        ),
        make(
            id: "public-indoor-calf-raise",
            scene: .publicIndoor,
            name: "提踵",
            type: .dynamicResistance,
            movementAdvice: """
            ① 双脚自然分开，身体站稳；
            ② 缓慢抬起脚跟；
            ③ 再慢慢落下，不要快速弹动。
            """,
            intensityAdvice: "动作时保持自然呼吸，并能说出简短句子。如果需要憋气、身体明显晃动或小腿抽痛，请减少次数并休息。",
            systemImageName: "figure.stand",
            assetImageName: "ExerciseCalfRaise",
            energyTier: .low,
            scores: scores(-1, 3, 1, 3, 1),
            order: 9
        ),
        make(
            id: "public-indoor-forward-back-tap",
            scene: .publicIndoor,
            name: "前后点步",
            type: .aerobic,
            movementAdvice: """
            ① 一只脚向前轻点地后收回；
            ② 同一只脚再向后轻点地，然后换脚；
            ③ 上身保持直立，全程不跳跃。
            """,
            intensityAdvice: "呼吸稍快，但仍能完整说话，不能轻松唱歌。如果脚步变乱、身体摇晃或说话断断续续，请缩小点步距离并放慢节奏。",
            systemImageName: "figure.dance",
            assetImageName: "ExerciseForwardBackTap",
            energyTier: .medium,
            scores: scores(1, 3, 3, 1, 1),
            order: 10
        ),
        make(
            id: "public-indoor-supported-side-leg-raise",
            scene: .publicIndoor,
            name: "扶墙侧抬腿",
            type: .dynamicResistance,
            movementAdvice: """
            ① 一手扶住墙面或稳固支撑；
            ② 一侧腿向侧方小幅抬起，脚尖朝前；
            ③ 缓慢落下，左右交替，身体不要侧倾。
            """,
            intensityAdvice: "动作时保持自然呼吸，并能说出简短句子。如果身体明显倾斜、髋部不适或无法缓慢落腿，请减小抬腿幅度或减少次数。",
            systemImageName: "figure.flexibility",
            assetImageName: "ExerciseSupportedSideLegRaise",
            energyTier: .low,
            scores: scores(-1, 3, 1, 3, 1),
            order: 11
        ),

        make(
            id: "public-outdoor-slow-walk",
            scene: .publicOutdoor,
            name: "慢走",
            type: .aerobic,
            movementAdvice: """
            ① 选择平坦、安全的路线；
            ② 保持自然步幅和稳定节奏；
            ③ 肩膀放松，脚步轻稳。
            """,
            intensityAdvice: "呼吸稍快，但仍能完整说话，不能轻松唱歌。如果只能说几个词，请立即放慢。",
            systemImageName: "figure.walk",
            assetImageName: "ExerciseSlowWalk",
            energyTier: .low,
            scores: scores(3, 3, 3, 3, 3),
            order: 12
        ),
        make(
            id: "public-outdoor-moderate-brisk-walk",
            scene: .publicOutdoor,
            name: "适度快走",
            type: .aerobic,
            movementAdvice: """
            ① 先慢走一段时间再逐渐加快；
            ② 比日常走路稍快，但不要竞速；
            ③ 步幅自然，手臂配合摆动。
            """,
            intensityAdvice: "可以完整说话，但不能轻松唱歌。如果说一句话需要多次换气，说明强度过高，应降低速度。",
            systemImageName: "figure.walk.motion",
            assetImageName: "ExerciseModerateBriskWalk",
            energyTier: .high,
            scores: scores(1, 1, 3, -3, -3),
            order: 13
        ),
        make(
            id: "public-outdoor-side-step",
            scene: .publicOutdoor,
            name: "侧向踏步",
            type: .aerobic,
            movementAdvice: """
            ① 确认地面平整、周围没有障碍；
            ② 左右缓慢移动，不要交叉双脚；
            ③ 身体面向前方，保持连续节奏。
            """,
            intensityAdvice: "呼吸稍快，但仍能完整说话，不能轻松唱歌。如果无法保持连续交谈，请缩小步幅或放慢。",
            systemImageName: "figure.cross.training",
            assetImageName: "ExerciseSideStep",
            energyTier: .medium,
            scores: scores(1, 3, 3, -1, -1),
            order: 14
        ),
        make(
            id: "public-outdoor-step-jack",
            scene: .publicOutdoor,
            name: "开合步",
            type: .aerobic,
            movementAdvice: """
            ① 一只脚向侧方迈开，再收回；
            ② 左右脚交替进行；
            ③ 双臂可自然抬起，但全程不要跳跃。
            """,
            intensityAdvice: "呼吸稍快，但仍能完整说话，不能轻松唱歌。如果只能说几个词，请减慢动作或暂时不抬手臂。",
            systemImageName: "figure.mixed.cardio",
            assetImageName: "ExerciseStepJack",
            energyTier: .high,
            scores: scores(-1, 3, 3, -3, -3),
            order: 15
        ),
        make(
            id: "public-outdoor-forward-back-tap",
            scene: .publicOutdoor,
            name: "前后点步",
            type: .aerobic,
            movementAdvice: """
            ① 选择平整、没有行人干扰的位置；
            ② 一只脚向前轻点后收回，再向后轻点；
            ③ 左右脚交替，上身保持直立。
            """,
            intensityAdvice: "呼吸稍快，但仍能完整说话，不能轻松唱歌。如果身体摇晃、脚步变乱或只能说几个词，请缩小动作范围并放慢。",
            systemImageName: "figure.dance",
            assetImageName: "ExerciseForwardBackTap",
            energyTier: .medium,
            scores: scores(1, 3, 3, 1, 1),
            order: 16
        ),
        make(
            id: "public-outdoor-low-step-up",
            scene: .publicOutdoor,
            name: "低台阶踏步",
            type: .aerobic,
            movementAdvice: """
            ① 选择稳固的低台阶，并尽量靠近扶手；
            ② 一只脚踏上，另一只脚跟上，再依次踏下；
            ③ 交替领先脚，保持稳定节奏，不要跳跃。
            """,
            intensityAdvice: "可以完整说话，但不能轻松唱歌。如果说话需要多次换气、膝部不适或上下台阶不稳，请降低速度、改用更低台阶或停止。",
            systemImageName: "figure.stairs",
            assetImageName: "ExerciseLowStepUp",
            energyTier: .high,
            scores: scores(-3, 1, 1, -3, -3),
            order: 17
        ),

        make(
            id: "private-open-outdoor-moderate-brisk-walk",
            scene: .privateOrOpenOutdoor,
            name: "适度快走",
            type: .aerobic,
            movementAdvice: """
            ① 先用慢走进行热身；
            ② 逐渐加快至舒适速度；
            ③ 结束前慢慢减速，不要突然停下。
            """,
            intensityAdvice: "可以完整说话，但不能轻松唱歌。如果无法连续说完一句话，请降低速度。",
            systemImageName: "figure.walk.motion",
            assetImageName: "ExerciseModerateBriskWalk",
            energyTier: .high,
            scores: scores(1, 1, 3, -3, -3),
            order: 18
        ),
        make(
            id: "private-open-outdoor-shallow-squat",
            scene: .privateOrOpenOutdoor,
            name: "浅蹲",
            type: .dynamicResistance,
            movementAdvice: """
            ① 双脚自然分开，脚尖朝前；
            ② 臀部向后下方移动；
            ③ 只蹲到舒适位置，再缓慢站起。
            """,
            intensityAdvice: "动作过程中应能正常呼吸并说出简短句子。如果需要憋气、膝盖不适或无法稳定站起，请减小下蹲幅度。",
            systemImageName: "figure.squat",
            assetImageName: "ExerciseShallowSquat",
            energyTier: .medium,
            scores: scores(-1, 3, -1, -1, -1),
            order: 19
        ),
        make(
            id: "private-open-outdoor-wall-push-up",
            scene: .privateOrOpenOutdoor,
            name: "靠墙俯卧撑",
            type: .dynamicResistance,
            movementAdvice: """
            ① 双手撑墙，略宽于肩；
            ② 弯曲手肘，让身体缓慢靠近墙面；
            ③ 推回时呼气，保持腰背稳定。
            """,
            intensityAdvice: "动作时保持呼吸，并能说出简短句子。如果需要屏住呼吸才能完成，请靠近墙面或减少次数。",
            systemImageName: "figure.strengthtraining.traditional",
            assetImageName: "ExerciseWallPushUp",
            energyTier: .medium,
            scores: scores(-1, 1, -1, 1, 1),
            order: 20
        ),
        make(
            id: "private-open-outdoor-wall-sit",
            scene: .privateOrOpenOutdoor,
            name: "靠墙静蹲",
            type: .isometric,
            movementAdvice: """
            ① 背部贴墙，双脚踩稳；
            ② 采用舒适的浅蹲角度；
            ③ 保持身体稳定，不追求蹲得更低。
            """,
            intensityAdvice: "采用浅角度、短时间保持，并在每次保持后充分休息；全程正常呼吸。如果无法说出短句、明显憋气、头晕或腿部剧烈发抖，请立即结束。不要把它设计成连续 10–20 分钟的保持动作。",
            systemImageName: "figure.strengthtraining.functional",
            assetImageName: "ExerciseWallSit",
            energyTier: .high,
            scores: scores(-3, -1, -3, -3, -3),
            order: 21
        ),
        make(
            id: "private-open-outdoor-supported-back-leg-raise",
            scene: .privateOrOpenOutdoor,
            name: "扶墙后抬腿",
            type: .dynamicResistance,
            movementAdvice: """
            ① 一手扶住墙面或稳固支撑；
            ② 一侧腿向后小幅抬起，膝盖保持自然；
            ③ 缓慢落下，左右交替，不要向后仰腰。
            """,
            intensityAdvice: "动作时保持自然呼吸，并能说出简短句子。如果腰部代偿、身体晃动或髋部不适，请减小抬腿幅度或减少次数。",
            systemImageName: "figure.flexibility",
            assetImageName: "ExerciseSupportedBackLegRaise",
            energyTier: .low,
            scores: scores(-1, 3, 1, 3, 1),
            order: 22
        ),
        make(
            id: "private-open-outdoor-low-step-up",
            scene: .privateOrOpenOutdoor,
            name: "低台阶踏步",
            type: .aerobic,
            movementAdvice: """
            ① 选择稳固的低台阶，并确保周围没有障碍；
            ② 一只脚踏上，另一只脚跟上，再依次踏下；
            ③ 交替领先脚，保持稳定节奏，不要跳跃。
            """,
            intensityAdvice: "可以完整说话，但不能轻松唱歌。如果无法连续说完一句话、膝部不适或动作不稳，请降低速度、换更低台阶或停止。",
            systemImageName: "figure.stairs",
            assetImageName: "ExerciseLowStepUp",
            energyTier: .high,
            scores: scores(-3, 1, 1, -3, -3),
            order: 23
        )
    ]

    static func exercises(in scene: ExerciseScene) -> [LowBarrierExercise] {
        all.filter { $0.scene == scene }
    }

    static func exercise(id: String) -> LowBarrierExercise? {
        all.first { $0.id == id }
    }

    private static func scores(
        _ afterMeal: Int,
        _ afterSitting: Int,
        _ afterStress: Int,
        _ sleepDeprived: Int,
        _ afterActivity: Int
    ) -> ExerciseContextScores {
        ExerciseContextScores(
            afterMeal: afterMeal,
            afterSitting: afterSitting,
            afterStress: afterStress,
            sleepDeprived: sleepDeprived,
            afterActivity: afterActivity
        )
    }

    private static func make(
        id: String,
        scene: ExerciseScene,
        name: String,
        type: ExerciseType,
        movementAdvice: String,
        intensityAdvice: String,
        systemImageName: String,
        assetImageName: String? = nil,
        energyTier: ExerciseEnergyTier,
        scores: ExerciseContextScores,
        order: Int
    ) -> LowBarrierExercise {
        let reviewedCopy = ExerciseInstructionCatalog.byExerciseID[id]
        return LowBarrierExercise(
            id: id,
            scene: scene,
            name: name,
            type: type,
            movementAdvice: reviewedCopy?.howTo ?? movementAdvice,
            intensityAdvice: reviewedCopy?.intensity ?? intensityAdvice,
            systemImageName: systemImageName,
            assetImageName: assetImageName,
            energyTier: energyTier,
            contextScores: scores,
            catalogOrder: order
        )
    }
}

enum ExerciseRecommendationEngine {
    /// UI-friendly adapter for the strings currently stored by ActionGenerateDemoView.
    static func recommendations(
        sceneTitle: String,
        energyTitle: String,
        contextTitles: Set<String>,
        limit: Int = 4
    ) -> [LowBarrierExercise] {
        guard let scene = ExerciseScene(title: sceneTitle),
              let energy = ExerciseEnergyTier(title: energyTitle) else {
            return []
        }

        let contexts = Set(contextTitles.compactMap(ExerciseContext.init(rawValue:)))
        return recommendations(scene: scene, energy: energy, contexts: contexts, limit: limit)
    }

    static func recommendations(
        scene: ExerciseScene,
        energy: ExerciseEnergyTier,
        contexts: Set<ExerciseContext>,
        limit: Int = 4
    ) -> [LowBarrierExercise] {
        rankedRecommendations(
            scene: scene,
            energy: energy,
            contexts: contexts,
            limit: limit
        ).map(\.exercise)
    }

    static func rankedRecommendations(
        scene: ExerciseScene,
        energy: ExerciseEnergyTier,
        contexts: Set<ExerciseContext>,
        limit: Int = 4
    ) -> [ExerciseRecommendation] {
        let candidates = LowBarrierExerciseCatalog.exercises(in: scene)
        let boundedLimit = max(0, min(limit, candidates.count))
        guard boundedLimit > 0 else { return [] }

        let scored = candidates.map { exercise -> ExerciseRecommendation in
            let energyScore = self.energyScore(selected: energy, exercise: exercise.energyTier)
            let contextScore = contexts.reduce(into: 0) { total, context in
                total += exercise.contextScores[context]
            }
            return ExerciseRecommendation(
                exercise: exercise,
                score: energyScore + contextScore,
                energyScore: energyScore,
                contextScore: contextScore
            )
        }
        .sorted { lhs, rhs in
            stableHigherScore(lhs, rhs)
        }

        var selected: [ExerciseRecommendation] = []
        for candidate in scored {
            if candidate.exercise.type == .isometric,
               selected.contains(where: { $0.exercise.type == .isometric }) {
                continue
            }
            selected.append(candidate)
            if selected.count == boundedLimit { break }
        }

        ensureCategoryBalance(
            selected: &selected,
            rankedCandidates: scored,
            catalog: candidates,
            limit: boundedLimit
        )

        return selected.sorted { lhs, rhs in
            stableHigherScore(lhs, rhs)
        }
    }

    private static func energyScore(
        selected: ExerciseEnergyTier,
        exercise: ExerciseEnergyTier
    ) -> Int {
        switch abs(selected.rawValue - exercise.rawValue) {
        case 0: return 4
        case 1: return 2
        default: return 0
        }
    }

    private static func stableHigherScore(
        _ lhs: ExerciseRecommendation,
        _ rhs: ExerciseRecommendation
    ) -> Bool {
        if lhs.score != rhs.score { return lhs.score > rhs.score }
        return lhs.exercise.catalogOrder < rhs.exercise.catalogOrder
    }

    private static func ensureCategoryBalance(
        selected: inout [ExerciseRecommendation],
        rankedCandidates: [ExerciseRecommendation],
        catalog: [LowBarrierExercise],
        limit: Int
    ) {
        guard limit >= 2,
              catalog.contains(where: { $0.type.isAerobic }),
              catalog.contains(where: { !$0.type.isAerobic }) else {
            return
        }

        let hasAerobic = selected.contains { $0.exercise.type.isAerobic }
        let hasNonAerobic = selected.contains { !$0.exercise.type.isAerobic }
        guard !hasAerobic || !hasNonAerobic else { return }

        let needsAerobic = !hasAerobic
        guard let replacement = rankedCandidates.first(where: { candidate in
            candidate.exercise.type.isAerobic == needsAerobic &&
                !selected.contains(where: { $0.id == candidate.id }) &&
                (candidate.exercise.type != .isometric ||
                    !selected.contains(where: { $0.exercise.type == .isometric }))
        }) else { return }

        let replaceableIndices = selected.indices.filter { index in
            selected[index].exercise.type.isAerobic != needsAerobic
        }
        guard let index = replaceableIndices.max(by: { lhs, rhs in
            stableHigherScore(selected[lhs], selected[rhs])
        }) else { return }

        selected[index] = replacement
    }
}
